#!/usr/bin/env bash
# Publish a rendered eval run to the eval-transcripts orphan branch.
#
#   scripts/publish-transcripts.sh <run-dir> <run-number> <status>
#   scripts/publish-transcripts.sh --prune-only <workdir> <keep>
#
# The mechanism is borrowed from ../mvp-bootstrap, which has been running it for
# 130-odd e2e runs: clone the branch into a temp dir, copy the run in, prune,
# commit, push with a rebase-retry. No GitHub Pages, no third-party action, no
# deploy key — just git and the job's GITHUB_TOKEN.
#
# Three things it does differently, each because the reference got bitten:
#
#   * Prunes by the run number parsed from the directory name, never by mtime.
#     After `git clone --depth=1` every archived directory carries the clone's
#     mtime, so an mtime sort deletes near-arbitrary runs.
#   * Clones into a temp dir, never `git checkout` in the workspace. Doing that
#     wiped src/ out from under a running job there and produced a
#     ModuleNotFoundError they never fixed, only worked around.
#   * Copies an explicit list. The orphan branch carries no .gitignore, so
#     `git add -A` on a wildcard would commit whatever happened to be lying
#     around.
#
# Extracted from the workflow so the pruning arithmetic is testable without CI.
set -euo pipefail

BRANCH="${TRANSCRIPT_BRANCH:-eval-transcripts}"
KEEP_DEFAULT=50

die() { echo "publish-transcripts: $*" >&2; exit 1; }

# --------------------------------------------------------------------------- #
# prune — keep the N highest run numbers
# --------------------------------------------------------------------------- #
prune_runs() {
    local workdir="$1" keep="$2"
    local runs="${workdir}/runs"
    [ -d "$runs" ] || return 0

    # Directory names look like 2026-10-01__run-42__gemini-3.8-flash. Sort by the
    # numeric field, keep the top N, delete the rest. Anything that does not
    # parse is left alone: deleting what we cannot identify is worse than
    # keeping it.
    local parsed=()
    local dir base num
    for dir in "$runs"/*/; do
        [ -d "$dir" ] || continue
        base="$(basename "$dir")"
        if [[ "$base" =~ __run-([0-9]+)__ ]]; then
            num="${BASH_REMATCH[1]}"
            parsed+=("${num} ${base}")
        fi
    done

    [ "${#parsed[@]}" -gt "$keep" ] || return 0

    local stale
    stale=$(printf '%s\n' "${parsed[@]}" | sort -k1,1nr | tail -n +$((keep + 1)) | cut -d' ' -f2-)
    while IFS= read -r base; do
        [ -n "$base" ] || continue
        echo "  pruning runs/${base}"
        rm -rf "${runs:?}/${base}"
    done <<< "$stale"
}

if [ "${1:-}" = "--prune-only" ]; then
    prune_runs "${2:?workdir}" "${3:-$KEEP_DEFAULT}"
    exit 0
fi

# --------------------------------------------------------------------------- #
# publish
# --------------------------------------------------------------------------- #
RUN_DIR="${1:?usage: publish-transcripts.sh <run-dir> <run-number> <status>}"
RUN_NUMBER="${2:?run number}"
STATUS="${3:-unknown}"

# The directory name carries the model, taken from what the run actually used
# rather than from a default that would drift the day SHRIMPY_MODEL changes.
# Derived here rather than in the workflow so it is testable without CI.
model_slug() {
    python3 - "$1" <<'PYEOF'
import json, pathlib, sys
path = pathlib.Path(sys.argv[1]) / "entries.json"
try:
    model = json.loads(path.read_text(encoding="utf-8"))["meta"].get("model")
except Exception:
    model = None
print((model or "unknown").replace("/", "-"))
PYEOF
}

RUN_LABEL="$(date -u +%Y-%m-%d)__run-${RUN_NUMBER}__$(model_slug "$RUN_DIR")"
KEEP="${TRANSCRIPT_KEEP:-$KEEP_DEFAULT}"

[ -d "$RUN_DIR" ] || die "no such run directory: $RUN_DIR"
[ -n "${GITHUB_REPOSITORY:-}" ] || die "GITHUB_REPOSITORY is not set"
[ -n "${GITHUB_TOKEN:-}" ] || die "GITHUB_TOKEN is not set"

workdir="$(mktemp -d "${RUNNER_TEMP:-/tmp}/transcripts.XXXXXX")"
trap 'rm -rf "$workdir"' EXIT

repo_url="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

# Shallow: the branch accumulates history forever and CI has no use for it.
if ! git clone --depth=1 --branch="$BRANCH" "$repo_url" "$workdir" 2>/dev/null; then
    echo "branch ${BRANCH} does not exist — creating it as an orphan"
    git clone --depth=1 "$repo_url" "$workdir"
    (
        cd "$workdir"
        git checkout --orphan "$BRANCH"
        git rm -rf . >/dev/null 2>&1 || true
        git clean -fdx >/dev/null 2>&1 || true
        mkdir -p runs
        cat > README.md <<'INIT'
# Eval transcripts

Rendered transcripts from `./shrimpy eval --live`, one directory per run.

Each run holds `index.md` (the summary), `cases/<case>.md` (the full exchange
with the assertions beside it) and `cases/<case>.json` (the raw messages, so a
renderer fix can re-render an archived run).

Generated by `scripts/publish-transcripts.sh`. Do not edit by hand — this branch
is written by CI and pruned automatically.
INIT
        git add -A && git commit -m "init ${BRANCH}" >/dev/null
    )
fi

dest="${workdir}/runs/${RUN_LABEL}"
rm -rf "$dest"
mkdir -p "$dest"
cp -r "${RUN_DIR}/." "$dest/"

prune_runs "$workdir" "$KEEP"

# Rolling index at the branch root, rebuilt from every run's entries.json.
if [ -f "${GITHUB_WORKSPACE:-$PWD}/scripts/render_branch_readme.py" ]; then
    python3 "${GITHUB_WORKSPACE:-$PWD}/scripts/render_branch_readme.py" "$workdir" \
        || echo "  (rolling README not regenerated)"
fi

(
    cd "$workdir"
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add -A
    if git diff --cached --quiet; then
        echo "nothing to publish"
        exit 0
    fi
    git commit -m "eval run ${RUN_LABEL} (${STATUS})" >/dev/null
    # One publisher today, so a race is unlikely — but a retry costs nothing and
    # a lost transcript is only noticed when it is wanted.
    for attempt in 1 2 3; do
        if git push origin "$BRANCH" >/dev/null 2>&1; then
            echo "published runs/${RUN_LABEL} to ${BRANCH}"
            exit 0
        fi
        echo "  push failed (attempt ${attempt}), rebasing"
        git pull --rebase origin "$BRANCH" >/dev/null 2>&1 || true
    done
    die "could not push to ${BRANCH}"
)
